### ISSUE TITLE
AttributeError: 'Etag' object has no attribute 'dependency' While using fastapi-etag

### ISSUE THREAD

**Issue by Mounika-12** [steinitzu/fastapi-etag#4]
I have created a file as _app.py_ as below
```
from fastapi import FastAPI,Depends
from starlette.requests import Request
from fastapi_etag import Etag, add_exception_handler

app = FastAPI()
add_exception_handler(app)


async def get_hello_etag(request: Request):
    name = request.path_params.get("name")
    return f"etagfor{name}"


@app.get("/hello/{name}", dependencies=[Etag(get_hello_etag)])
def hello(name: str):
    return {"hello": name}
```
When I run the file _uvicorn app:app --reload --host 0.0.0.0 --port 6002_ I am getting below error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/test/.local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/home/test/.local/lib/python3.7/site-packages/uvicorn/main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/test/.local/lib/python3.7/site-packages/uvicorn/main.py", line 389, in serve
    config.load()
  File "/home/test/.local/lib/python3.7/site-packages/uvicorn/config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/test/.local/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./app.py", line 15, in <module>
    def hello(name: str):
  File "/home/test/.local/lib/python3.7/site-packages/fastapi/routing.py", line 539, in decorator
    callbacks=callbacks,
  File "/home/test/.local/lib/python3.7/site-packages/fastapi/routing.py", line 479, in add_api_route
    callbacks=callbacks,
  File "/home/test/.local/lib/python3.7/site-packages/fastapi/routing.py", line 374, in __init__
    get_parameterless_sub_dependant(depends=depends, path=self.path_format),
  File "/home/test/.local/lib/python3.7/site-packages/fastapi/dependencies/utils.py", line 118, in get_parameterless_sub_dependant
    depends.dependency
AttributeError: 'Etag' object has no attribute 'dependency' 
```
Please help me how to resolve the issue.

**Comment by thomasleveil** [comment]
```python
@app.get("/hello/{name}", dependencies=[Etag(get_hello_etag)])
```

should be

```python
@app.get("/hello/{name}", dependencies=[Depends(Etag(get_hello_etag))])
```

**Comment by Mounika-12** [comment]
> ```python
> @app.get("/hello/{name}", dependencies=[Etag(get_hello_etag)])
> ```
> 
> should be
> 
> ```python
> @app.get("/hello/{name}", dependencies=[Depends(Etag(get_hello_etag))])
> ```

Thank you it's working. I think this line should get updated in the [https://pypi.org/project/fastapi-etag/](url) also.
